// Defect catalogue. Every entry was reproduced by hand on the staging
// environment; `tests` lists the automated test cases that reproduce it on
// each run (empty = found during exploratory testing, no automated check).
const DSH = "Dashboard";
const ORG = "Organization";
const SUP = "Sign Up";
const ANN = "Announcements";
const SEC = "Cross-module";

const LOGIN = "Logged in as tester@krystalhr.com (Super Admin).";

module.exports = [
  // ------------------------------------------------------------ Critical
  {
    id: "BUG-001",
    module: SEC,
    area: "Log Viewer",
    title: "Server logs (including emails with admin passwords) can be read without logging in",
    severity: "Critical",
    priority: "P1",
    type: "Security",
    preconditions: "No session: use a private window or curl.",
    steps: "1. Request GET /log-viewer/api/files with header Accept: application/json.\n2. Take the identifier of laravel-{date}.log from the response.\n3. Request GET /log-viewer/api/logs?file={identifier}&per_page=1.",
    expected: "Both requests are refused (redirect to /auth/login or 401/403), like the /log-viewer page itself, which does redirect.",
    actual: "Both return HTTP 200. The first lists 105 server log files (nginx + Laravel) flagged can_download: true and can_delete: true; the second returns log entries. The Laravel log holds every email the system sends, including 'Admin Account Created' emails with plain-text passwords (BUG-002).",
    evidence: "Automated: SEC-002. Manual: curl without cookies returned 200 for both endpoints. Delete was not attempted.",
    tests: ["SEC-002"],
  },

  // ------------------------------------------------------------ High
  {
    id: "BUG-002",
    module: ORG,
    area: "Add Organization / emails",
    title: "Admin password is emailed in plain text and is predictable (first name + last 4 phone digits)",
    severity: "High",
    priority: "P1",
    type: "Security",
    preconditions: LOGIN,
    steps: "1. Organizations > Add Organization.\n2. Admin Contact: First Name 'Ada', Phone '08031234568'; complete the form and save.\n3. Open /log-viewer > laravel-{date}.log and find 'Admin Account Created' sent to the admin email.",
    expected: "A set-password link (or a random one-time password). Credentials must not be derivable from data the admin entered.",
    actual: "The email contains 'Password: ada4568' (lower-case first name + last four digits of the admin phone). Same pattern for every admin created (pat4571, grace4570, 12344569). The same password is re-sent on Activate, Approve and Resend Details.",
    evidence: "Automated: ORG-016. Log entries 2026-10-09 14:42:33, 14:48:34, 14:51:04.",
    tests: ["ORG-016"],
  },
  {
    id: "BUG-003",
    module: SUP,
    area: "Review Organization",
    title: "'Reject' in the Review dialog does nothing",
    severity: "High",
    priority: "P1",
    type: "Functional",
    preconditions: LOGIN + " At least one pending sign-up.",
    steps: "1. Sign Ups > click 'Review' on a pending organization.\n2. Click 'Reject'.",
    expected: "The registration is rejected: it leaves the pending list (and the applicant is informed).",
    actual: "Nothing happens. No request is sent to the server, no message is shown, the dialog stays open and the organization remains Pending in Sign Ups and Organizations. The button is a plain submit button inside a form with no handler.",
    evidence: "Automated: SUP-012.",
    tests: ["SUP-012"],
  },
  {
    id: "BUG-004",
    module: ORG,
    area: "Add Organization",
    title: "Add Organization fails silently when the Domain Prefix is invalid (error is never displayed)",
    severity: "High",
    priority: "P1",
    type: "Functional",
    preconditions: LOGIN,
    steps: "1. Organizations > Add Organization.\n2. Fill all fields with valid data; Domain Prefix = 'qamcdomain123' (13 characters).\n3. Tick the consent box and click 'Save changes'.",
    expected: "The Domain Prefix validation message is shown under the field (as for every other field).",
    actual: "The form stays open with no message at all and nothing is created. The server does return 'The domain prefix field must not be greater than 10 characters.', but the field has no error slot. Also reproduced with 'The domain prefix field must only contain letters and numbers.' and 'The domain has already been taken.' The field has no maxlength or hint about the 10-character limit.",
    evidence: "Automated: ORG-010 (compares the server's message with the page).",
    tests: ["ORG-010"],
  },
  {
    id: "BUG-005",
    module: ORG,
    area: "Manage > Billing and Subscription",
    title: "'Change Plan' cannot be saved",
    severity: "High",
    priority: "P1",
    type: "Functional",
    preconditions: LOGIN + " An organization on the Free plan.",
    steps: "1. Organizations > Manage > 'Billing and Subscription'.\n2. Click 'Change Plan', select 'Basic'.\n3. Click 'Save changes'.",
    expected: "The plan is updated to Basic and the dialog closes with a confirmation.",
    actual: "Nothing happens: no request is sent, the dialog stays open, and the organization is still on Free in the list.",
    evidence: "Automated: ORG-028.",
    tests: ["ORG-028"],
  },
  {
    id: "BUG-006",
    module: ORG,
    area: "Organization list (also Dashboard > Companies)",
    title: "The same organization appears on several pages of the list while others are skipped",
    severity: "High",
    priority: "P2",
    type: "Data integrity",
    preconditions: LOGIN + " Many organizations share the same sign-up timestamp (e.g. bulk import).",
    steps: "1. Open /organizations?page=2, ?page=3 and ?page=4 with the default sort (Newest).\n2. Compare the organizations listed on each page.",
    expected: "Each organization appears on exactly one page.",
    actual: "Records repeat across pages (e.g. #941 'QA Bulk 0467' on pages 2 and 3; #949-#951 on pages 2 and 4), so other records are never shown. The order is not stable for rows with equal dates; a secondary sort key (ID) is missing.",
    evidence: "Automated: ORG-006.",
    tests: ["ORG-006"],
  },
  {
    id: "BUG-007",
    module: SUP,
    area: "Emails on registration",
    title: "A pending (unapproved) organization already receives the welcome email and admin login credentials",
    severity: "High",
    priority: "P2",
    type: "Functional",
    preconditions: LOGIN,
    steps: "1. Add an organization with the 'Organization Status' switch OFF (it is created as Pending and appears in Sign Ups).\n2. Open /log-viewer and list the emails for that organization.",
    expected: "Only 'Your Application Has Been Received'. Welcome and credentials are sent after approval.",
    actual: "Four emails at once: 'Your Application Has Been Received', 'New Company Signup - Review Required' (to business@), and also 'Welcome to KrystalHR - your organisation account has been successfully created and is ready to use' plus 'Admin Account Created' with the admin's password. The applicant is told both 'we will revert within 24 hours' and 'your account is ready'.",
    evidence: "Automated: SUP-006. Log entries 2026-10-09 14:42:33 and 14:51:01.",
    tests: ["SUP-006"],
  },

  // ------------------------------------------------------------ Medium
  {
    id: "BUG-008",
    module: SUP,
    area: "Review Organization > Approve",
    title: "Approving a sign-up sends every onboarding email twice",
    severity: "Medium",
    priority: "P2",
    type: "Functional",
    preconditions: LOGIN + " A pending sign-up.",
    steps: "1. Sign Ups > Review > Approve.\n2. Open /log-viewer and list the emails logged at that second.",
    expected: "One welcome email to the organization and one account email to the admin.",
    actual: "Two 'Welcome to KrystalHR' emails and two 'Admin Account Created' emails are sent in the same second.",
    evidence: "Automated: SUP-014. Log entries 2026-10-09 14:52:13 (4 emails).",
    tests: ["SUP-014"],
  },
  {
    id: "BUG-009",
    module: ORG,
    area: "Emails on creation",
    title: "An organization created as Active still triggers the 'application received / review required' emails",
    severity: "Medium",
    priority: "P3",
    type: "Functional",
    preconditions: LOGIN,
    steps: "1. Add an organization with the 'Organization Status' switch ON.\n2. Open /log-viewer and list the emails for that organization.",
    expected: "Welcome and admin-account emails only: the organization is already active.",
    actual: "The organization also gets 'Your Application Has Been Received ... we would revert within the next 24 hours', and business@krystalhr.com gets 'New Company Signup - Review Required', although nothing is left to review.",
    evidence: "Automated: ORG-018. Log entries 2026-10-09 14:45:06.",
    tests: ["ORG-018"],
  },
  {
    id: "BUG-010",
    module: ORG,
    area: "Manage > Organization Details; Sign Ups > Review",
    title: "Industry is shown as a number instead of its name",
    severity: "Medium",
    priority: "P2",
    type: "UI / Data",
    preconditions: LOGIN + " An organization created with industry 'Technology'.",
    steps: "1. Organizations > Manage on that organization and read 'Industry'.\n2. For a pending one: Sign Ups > Review and read 'Industry'.",
    expected: "'Technology' (the option chosen at creation).",
    actual: "The field shows the internal ID: '1' for Technology, '2' for Fashion, '4' for Finance.",
    evidence: "Automated: ORG-022, SUP-011.",
    tests: ["ORG-022", "SUP-011"],
  },
  {
    id: "BUG-011",
    module: ORG,
    area: "Manage > Edit Info",
    title: "Edit Info offers a different industry list and preselects 'Photography'",
    severity: "Medium",
    priority: "P2",
    type: "Functional",
    preconditions: LOGIN + " An organization created with industry 'Technology'.",
    steps: "1. Organizations > Manage > 'Edit Info'.\n2. Open the Industry dropdown.",
    expected: "The 15 industries of the Add form (Technology, Fashion, Healthcare, ...) with the saved one selected.",
    actual: "A different list is offered (Photography, Design services, Web development, Accounting, Legal services, Consulting, Other) and 'Photography' is preselected. The saved industry cannot be kept visible or re-selected, and choosing an option stores a text value where the rest of the app uses numeric IDs.",
    evidence: "Automated: ORG-023.",
    tests: ["ORG-023"],
  },
  {
    id: "BUG-012",
    module: ORG,
    area: "Add Organization",
    title: "The mandatory 'ID Prefix' is ignored",
    severity: "Medium",
    priority: "P2",
    type: "Functional",
    preconditions: LOGIN,
    steps: "1. Add an organization named 'QAMC Active ...' with ID Prefix 'ZQX'.\n2. Read the Employee ID in the 'Admin Account Created' email.\n3. Export CSV and read the 'ID prefix' column.",
    expected: "Employee IDs start with 'ZQX' and the export shows 'ZQX'.",
    actual: "The Employee ID is 'QAM261370': the first three letters of the organization name are used instead. The 'ID prefix' column of the export is empty for all organizations.",
    evidence: "Automated: ORG-017, ORG-033.",
    tests: ["ORG-017", "ORG-033"],
  },
  {
    id: "BUG-013",
    module: ORG,
    area: "Export CSV",
    title: "Export CSV leaves the 'Plan' and 'ID prefix' columns empty",
    severity: "Medium",
    priority: "P3",
    type: "Data integrity",
    preconditions: LOGIN,
    steps: "1. Organizations > Export CSV > OK.\n2. Open companies.csv.",
    expected: "'Plan' shows Free / Basic / Premium as in the list; 'ID prefix' shows the saved prefix.",
    actual: "Both columns are empty in all ~950 rows, although the list shows Basic and Premium plans. 'Domain' and 'Web Prefix' contain the same value. The column set also differs from the import template, so an export cannot be re-imported.",
    evidence: "Automated: ORG-033.",
    tests: ["ORG-033"],
  },
  {
    id: "BUG-014",
    module: DSH,
    area: "KPI cards",
    title: "Trend badges show the same unit-less figure on 'Total' and 'Pending' organizations",
    severity: "Medium",
    priority: "P3",
    type: "UI / Data",
    preconditions: LOGIN,
    steps: "1. Open /dashboard.\n2. Compare the green badge on 'Total Organizations' and on 'Pending Organizations'.",
    expected: "Each card shows its own change with a unit and period (e.g. '+4% vs last month').",
    actual: "Both badges show the identical value with no unit or period. The value follows the total (1870.83 at 946 organizations, 1879.17 at 950), so the Pending card displays the Total card's growth. 'Total Users' has no badge.",
    evidence: "Automated: DSH-006.",
    tests: ["DSH-006"],
  },
  {
    id: "BUG-015",
    module: DSH,
    area: "Action Required",
    title: "'Action Required' shows placeholder data and 'View all' does nothing",
    severity: "Medium",
    priority: "P2",
    type: "Functional",
    preconditions: LOGIN,
    steps: "1. Open /dashboard and read the 'Action Required' panel.\n2. Search the listed names in the Companies table.\n3. Click 'View all'.",
    expected: "Alerts for real organizations whose subscription is about to expire; 'View all' opens the full list.",
    actual: "The panel always lists 'Global Marketing', 'Product Launch' and 'Customer Support' (3 / 5 / 10 days). None of them exists as an organization. 'View all' has no action: no navigation, dialog or request.",
    evidence: "Automated: DSH-007, DSH-008.",
    tests: ["DSH-007", "DSH-008"],
  },
  {
    id: "BUG-016",
    module: ORG,
    area: "Manage > Billing and Subscription",
    title: "Billing history shows a template row and its download actions are dead",
    severity: "Medium",
    priority: "P3",
    type: "Functional",
    preconditions: LOGIN + " A Free-plan organization created today.",
    steps: "1. Organizations > Manage > 'Billing and Subscription'.\n2. Click 'Download' on the row and 'Download All'.",
    expected: "The organization's own invoices (none for a new Free organization), with working downloads.",
    actual: "Each organization checked shows the same row: 'Basic Plan | DD - MM- YYYY | ₦100,000 | Active'. 'Download' links to '#' and 'Download All' sends no request. Amounts are in ₦ here but in $ in the Change Plan dialog.",
    evidence: "Automated: ORG-029.",
    tests: ["ORG-029"],
  },
  {
    id: "BUG-017",
    module: ORG,
    area: "Add Organization",
    title: "Hint says 'activated immediately' while the status switch is off and the organization is created Pending",
    severity: "Medium",
    priority: "P3",
    type: "UI",
    preconditions: LOGIN,
    steps: "1. Organizations > Add Organization.\n2. Leave 'Organization Status' off and read the text under it.\n3. Save a valid organization.",
    expected: "The hint describes the current switch position (off = pending approval).",
    actual: "The hint always reads 'Organization will be activated immediately upon creation', but with the switch off the organization is created as Pending and lands in Sign Ups.",
    evidence: "Automated: ORG-011.",
    tests: ["ORG-011"],
  },
  {
    id: "BUG-018",
    module: SUP,
    area: "Contact Organization",
    title: "Missing Title is not reported in the Contact dialog",
    severity: "Medium",
    priority: "P3",
    type: "Validation",
    preconditions: LOGIN + " A pending sign-up.",
    steps: "1. Sign Ups > Contact.\n2. Click 'Send Email' with Title and Message empty.\n3. Type a message only and click 'Send Email' again.",
    expected: "A required message under Title and under Message.",
    actual: "Only 'The contact.message field is required.' is shown. The Title error returned by the server is not displayed, so with a message typed the button appears to do nothing.",
    evidence: "Automated: SUP-007.",
    tests: ["SUP-007"],
  },
  {
    id: "BUG-019",
    module: SUP,
    area: "Contact Organization",
    title: "Contact dialog keeps the previous title and message after sending",
    severity: "Medium",
    priority: "P3",
    type: "Functional",
    preconditions: LOGIN + " A pending sign-up.",
    steps: "1. Sign Ups > Contact, enter a title and message, click 'Send Email'.\n2. Click 'Contact' again.",
    expected: "An empty form.",
    actual: "Title and Message still hold the text that was just sent, which makes it easy to send an old message again or to another organization.",
    evidence: "Automated: SUP-009.",
    tests: ["SUP-009"],
  },
  {
    id: "BUG-020",
    module: ANN,
    area: "Create Announcement > To",
    title: "Pending and suspended organizations can be chosen as announcement recipients",
    severity: "Medium",
    priority: "P3",
    type: "Functional",
    preconditions: LOGIN + " A pending sign-up and a suspended organization exist.",
    steps: "1. Announcements > Send Email.\n2. Open 'To' and search the name of a pending (or suspended) organization.",
    expected: "Only active organizations are offered. (To be confirmed with the product owner.)",
    actual: "Pending and suspended organizations are listed in the dropdown and can be selected.",
    evidence: "Automated: ANN-011.",
    tests: ["ANN-011"],
  },
  {
    id: "BUG-021",
    module: ANN,
    area: "Announcement list",
    title: "A long title pushes Sender, Recipients, Date Sent and Actions off the screen",
    severity: "Medium",
    priority: "P3",
    type: "UI",
    preconditions: LOGIN + " An announcement with a ~255-character title without spaces is on the page.",
    steps: "1. Open /announcements at 1280 px width.\n2. Go to the page that lists the long-title announcement.",
    expected: "Long titles wrap or are truncated; all five columns stay visible.",
    actual: "The Title column takes the width of the longest title, so for every row only the title is visible; 'View Details' can only be reached by scrolling the table sideways.",
    evidence: "Automated: ANN-019.",
    tests: ["ANN-019"],
  },

  // ------------------------------------------------------------ Low
  {
    id: "BUG-022",
    module: ORG,
    area: "Search (Organizations, Dashboard, Sign Ups, Announcements)",
    title: "Search does not trim spaces",
    severity: "Low",
    priority: "P4",
    type: "Functional",
    preconditions: LOGIN,
    steps: "1. Open /organizations.\n2. Search an existing name with a leading or trailing space (e.g. pasted text).",
    expected: "The organization is found.",
    actual: "'No companies found.' Same behaviour in Sign Ups and Announcements. Also, '%' is treated as a wildcard and returns every record.",
    evidence: "Automated: ORG-003.",
    tests: ["ORG-003"],
  },
  {
    id: "BUG-023",
    module: ORG,
    area: "Organization list",
    title: "Sort by Name is not alphabetical (names stored with leading spaces sort first)",
    severity: "Low",
    priority: "P4",
    type: "Functional",
    preconditions: LOGIN,
    steps: "1. Open /organizations.\n2. Choose Sort by > Name.",
    expected: "A to Z by organization name.",
    actual: "'Ewing Manning Co' and 'Ruby & Topaz' are listed before 'Abdullahi Systems'. The export shows these names are stored with leading / trailing spaces ('   Ewing Manning Co   '): names are not trimmed when saved through at least one entry point (Edit Info does trim).",
    evidence: "Automated: ORG-005.",
    tests: ["ORG-005"],
  },
  {
    id: "BUG-024",
    module: ORG,
    area: "Manage page header",
    title: "Organization name is almost unreadable in the Manage header (light theme)",
    severity: "Low",
    priority: "P3",
    type: "UI / Accessibility",
    preconditions: LOGIN + " Light theme.",
    steps: "1. Organizations > Manage on any organization.\n2. Look at the name and email under the avatar.",
    expected: "Readable text, contrast of at least 4.5:1.",
    actual: "Dark text rgb(29,41,57) on a near-black panel rgb(16,16,16): contrast 1.29:1.",
    evidence: "Automated: ORG-031.",
    tests: ["ORG-031"],
  },
  {
    id: "BUG-025",
    module: ORG,
    area: "Add Organization",
    title: "'Organization Logo*' is marked required but is optional",
    severity: "Low",
    priority: "P4",
    type: "Validation",
    preconditions: LOGIN,
    steps: "1. Organizations > Add Organization.\n2. Save a valid organization without a logo.",
    expected: "Either a 'logo is required' message, or no asterisk on the label.",
    actual: "The organization is created without a logo and no message is shown.",
    evidence: "Automated: ORG-009.",
    tests: ["ORG-009"],
  },
  {
    id: "BUG-026",
    module: ORG,
    area: "Add Organization",
    title: "Admin first / last name accept digits and HTML",
    severity: "Low",
    priority: "P4",
    type: "Validation",
    preconditions: LOGIN,
    steps: "1. Add an organization with admin First Name '1234' and Last Name '<b>x</b>'.",
    expected: "Names are limited to letters and common name punctuation.",
    actual: "The organization is created; emails greet the admin with 'Hello 1234' and the generated password becomes '12344569'. (The HTML is escaped on screen.)",
    evidence: "Automated: ORG-015.",
    tests: ["ORG-015"],
  },
  {
    id: "BUG-027",
    module: ORG,
    area: "Manage > Admins",
    title: "Admin 'Manage' link does nothing; Role is blank and Permissions is always 'Gallery Management'",
    severity: "Low",
    priority: "P3",
    type: "Functional",
    preconditions: LOGIN,
    steps: "1. Organizations > Manage > Admins.\n2. Read the Role and Permissions columns and click 'Manage' on a row.",
    expected: "The admin's role and permissions, and a working Manage action.",
    actual: "'Manage' is a link to '#'. Role is empty and Permissions shows 'Gallery Management' for every admin of every organization.",
    evidence: "Automated: ORG-027.",
    tests: ["ORG-027"],
  },
  {
    id: "BUG-028",
    module: ORG,
    area: "Add Organization",
    title: "Subscription Plan dropdown only offers 'Free'",
    severity: "Low",
    priority: "P3",
    type: "Functional",
    preconditions: LOGIN,
    steps: "1. Organizations > Add Organization.\n2. Open 'Subscription Plan'.",
    expected: "Free, Basic and Premium (plans shown in the list and in Change Plan).",
    actual: "'Free' is the only option. Together with BUG-005 there is no way in the UI to put an organization on a paid plan.",
    evidence: "Automated: ORG-012.",
    tests: ["ORG-012"],
  },
  {
    id: "BUG-029",
    module: ORG,
    area: "Organization list",
    title: "Organization name link leads to a tenant URL that fails to load",
    severity: "Low",
    priority: "P4",
    type: "Environment",
    preconditions: LOGIN,
    steps: "1. In /organizations click an organization name (e.g. https://qac9661660.krystalhrsite.kdns.site).",
    expected: "The tenant's site opens.",
    actual: "The connection fails with a TLS error (unrecognized name) for every tenant sub-domain tried. Possibly a staging certificate limitation; note the Add form also labels the suffix '.krystalhr.com' while links use '.krystalhrsite.kdns.site'.",
    evidence: "Automated: ORG-036.",
    tests: ["ORG-036"],
  },
  {
    id: "BUG-030",
    module: SUP,
    area: "Sign-up list",
    title: "No empty-state message when a search has no results",
    severity: "Low",
    priority: "P4",
    type: "UI",
    preconditions: LOGIN,
    steps: "1. Open /sign-ups.\n2. Search text that matches nothing.",
    expected: "A message such as 'No sign ups found.', as Organizations ('No companies found.') and Announcements do.",
    actual: "The table body is simply empty under the header row.",
    evidence: "Automated: SUP-004.",
    tests: ["SUP-004"],
  },
  {
    id: "BUG-031",
    module: SUP,
    area: "Sign-up list",
    title: "Sort label changes to 'Latest' after choosing 'Newest'",
    severity: "Low",
    priority: "P4",
    type: "UI",
    preconditions: LOGIN,
    steps: "1. Open /sign-ups (label: 'Sort by:Newest').\n2. Open the sort menu and choose 'Newest'.",
    expected: "'Sort by:Newest'.",
    actual: "'Sort by:Latest': the internal filter value is shown instead of the option label.",
    evidence: "Automated: SUP-015.",
    tests: ["SUP-015"],
  },
  {
    id: "BUG-032",
    module: ANN,
    area: "Announcement details",
    title: "Details page is headed 'Send Announcement'",
    severity: "Low",
    priority: "P4",
    type: "UI",
    preconditions: LOGIN,
    steps: "1. Announcements > 'View Details' on any row.",
    expected: "A heading that names the page (e.g. 'Announcement Details') and a breadcrumb back to Announcements.",
    actual: "The card heading reads 'Send Announcement' although nothing can be sent here; the breadcrumb is 'Home > Announcement Details' with no link to the list, and the body shows an editor toolbar on read-only content.",
    evidence: "Automated: ANN-016.",
    tests: ["ANN-016"],
  },
  {
    id: "BUG-033",
    module: ANN,
    area: "Announcement list",
    title: "Search only matches the title, not the sender",
    severity: "Low",
    priority: "P4",
    type: "Enhancement",
    preconditions: LOGIN,
    steps: "1. Open /announcements.\n2. Search 'support@krystalhr.com' (a value shown in the Sender column).",
    expected: "Announcements from that sender.",
    actual: "'No announcements found.'",
    evidence: "Automated: ANN-003.",
    tests: ["ANN-003"],
  },

  // ------------------------------------------------------------ Low, exploratory only
  {
    id: "BUG-034",
    module: ORG,
    area: "Validation messages (Edit Info, Add New Admin, Contact Organization)",
    title: "Validation messages expose internal field names",
    severity: "Low",
    priority: "P4",
    type: "UI",
    preconditions: LOGIN,
    steps: "1. Manage > Edit Info: enter -9 employees and Save.\n2. Manage > Admins > Add New Admin: click 'Create User' empty.\n3. Sign Ups > Contact: click 'Send Email' empty.",
    expected: "Plain-language messages ('Number of employees must be at least 1').",
    actual: "'The edit.number of employees field must be at least 1.', 'The admin.first name field is required.', 'The contact.message field is required.'",
    evidence: "Exploratory; visible in the screenshots of ORG-024, ORG-026 and SUP-007.",
    tests: [],
  },
  {
    id: "BUG-035",
    module: SUP,
    area: "Contact Organization",
    title: "Message placeholder is copied from a recruitment screen",
    severity: "Low",
    priority: "P4",
    type: "UI",
    preconditions: LOGIN,
    steps: "1. Sign Ups > Contact and read the Message placeholder.",
    expected: "A placeholder about contacting a registering organization.",
    actual: "'Provide interview details, including format, expectations, date, and time, along with any important instructions for candidates.' The upload is also labelled 'Descriptive Image'.",
    evidence: "Exploratory.",
    tests: [],
  },
  {
    id: "BUG-036",
    module: ORG,
    area: "Manage page header",
    title: "Activate / Suspend on the Manage page act without confirmation",
    severity: "Low",
    priority: "P4",
    type: "UI",
    preconditions: LOGIN,
    steps: "1. Organizations > Manage.\n2. Click 'Suspend' (or 'Activate') in the header.",
    expected: "The same 'Confirm Action' dialog used by the list.",
    actual: "The status changes immediately on one click.",
    evidence: "Exploratory.",
    tests: [],
  },
  {
    id: "BUG-037",
    module: ORG,
    area: "Add Organization",
    title: "Emails on domains without mail records are rejected as 'must be a valid email address'",
    severity: "Low",
    priority: "P4",
    type: "Validation",
    preconditions: LOGIN,
    steps: "1. Add an organization with email 'name@example.com'.",
    expected: "Accepted, or a message that explains the domain cannot receive mail.",
    actual: "'The organization email field must be a valid email address.' although the address is well-formed; the same form accepts '@mailinator.com'. Existing bulk-created organizations do have '@example.com' addresses, so entry points disagree.",
    evidence: "Exploratory.",
    tests: [],
  },
  {
    id: "BUG-038",
    module: ORG,
    area: "Import CSV",
    title: "Import error toast does not say which rows failed and omits some errors",
    severity: "Low",
    priority: "P4",
    type: "UI",
    preconditions: LOGIN,
    steps: "1. Import a CSV with one valid row, one row with a bad email and -4 employees, and one row re-using an existing domain prefix.",
    expected: "A per-row report (row number, field, reason).",
    actual: "Toasts '1 companies created successfully.' and '2 row(s) failed to import.The email field must be a valid email address., The number of employees field must be at least 1.' No row numbers are given and the duplicate-domain reason is missing.",
    evidence: "Exploratory.",
    tests: [],
  },
  {
    id: "BUG-039",
    module: SUP,
    area: "Emails on registration",
    title: "'New Company Signup' email is sometimes sent with an empty Admin Name",
    severity: "Low",
    priority: "P4",
    type: "Functional",
    preconditions: LOGIN,
    steps: "1. Add several pending organizations.\n2. Read the 'New Company Signup - Review Required' emails sent to business@krystalhr.com.",
    expected: "'Admin Name: Pat Pending'.",
    actual: "Intermittent (1 of 4 observed): 'Admin Name:' is blank. In that case the admin account email was logged three seconds after the notification, so the notification appears to be built before the admin exists.",
    evidence: "Exploratory. Log entry 2026-10-09 14:51:01.",
    tests: [],
  },
];
